name : issue_workflow
on : 
  issues : 
    types : [opened]

jobs :
  issues-job:
    runs-on: ubuntu-latest
    steps : 
    - name : 1st_step
      run : echo Hello
    - naem : 2nd_step
      run : |
        echo Hi
        echo Greeting

