name : needs_workflow
on : push

jobs:
  build :
    runs-on : ubuntu-latest
    steps :
    - name : 1st_build_step
      run : echo "1st build step start"

  test :
    runs-on : ubuntu-latest
    needs : [build]
    steps :
    - name : 1st_test_step
      run : echo "1st test step start"
  
  build_exit:
    runs-on : ubuntu-latest
    steps :
    - name : 2nd_build_exit_step
      run : |
        echo "2nd build exit step start"
        exit 1 

  test_exit :
    runs-on : ubuntu-latest
    needs : [build_exit]
    steps :
    - name : 2nd_test_exit_step
      run : echo "2nd test exit step start"




