name : Output for Step to Step Workflow
on : push

jobs :
  step-to-step:
    runs-on : ubuntu-latest
    steps:
      - id : insert-output
        run : echo "version=1.2.3" >> "$GITHUB_OUTPUT"
      - name : use output
        run : echo "output is ${{steps.insert-output.output.version}}"
  